version: "3.9"
services:
  web:
    image: nginx:1.21.6-alpine
    volumes:
      - ./templates:/etc/nginx/templates
    depends_on:
      - app_srv1
      - app_srv2
    ports:
      - "8080:80"
    environment:
      - NGINX_PORT=80
      - APP_HOST_1=app_srv1
      - APP_PORT_1=80
      - APP_HOST_2=app_srv2
      - APP_PORT_2=80

  app_srv1:
    build: ../
    image: oliversavio/api:latest
  app_srv2:
    build: ../
    image: oliversavio/api:latest
